version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-backend:
    image: aarchish/firewall-automation-spring-backend:latest
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  react-frontend:
    image: aarchish/firewall-automation-react-frontend:latest
    container_name: react-frontend
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - spring-backend

volumes:
  mysql_data: