name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 'Set up latest Oracle JDK 23'
      uses: oracle-actions/setup-java@v1
      with:
        website: oracle.com
        release: 23

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Build Spring Boot Backend
      run: |
        cd Spring-Backend
        mvn clean package -Dmaven.skip.tests=true -Ppublic

    - name: Build React Frontend
      run: |
        cd React-Frontend
        npm install
        npm run build

    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        port: 22
        script: |
          git pull
          docker-compose down
          docker-compose up -d --build